create table data_theloai (
	ma_tloai INT,
	ten_tloai TEXT
);
insert into data_theloai (ma_tloai, ten_tloai) values (340, 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac');
insert into data_theloai (ma_tloai, ten_tloai) values (14, 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est');
insert into data_theloai (ma_tloai, ten_tloai) values (118, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet');
insert into data_theloai (ma_tloai, ten_tloai) values (23, 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into data_theloai (ma_tloai, ten_tloai) values (764, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper');
insert into data_theloai (ma_tloai, ten_tloai) values (405, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc');
insert into data_theloai (ma_tloai, ten_tloai) values (631, 'donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio');
insert into data_theloai (ma_tloai, ten_tloai) values (19, 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla');
insert into data_theloai (ma_tloai, ten_tloai) values (47, 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into data_theloai (ma_tloai, ten_tloai) values (244, 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla');
insert into data_theloai (ma_tloai, ten_tloai) values (689, 'sed accumsan felis ut at dolor quis odio consequat varius');
insert into data_theloai (ma_tloai, ten_tloai) values (426, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi');
insert into data_theloai (ma_tloai, ten_tloai) values (739, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into data_theloai (ma_tloai, ten_tloai) values (114, 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi');
insert into data_theloai (ma_tloai, ten_tloai) values (94, 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat');
insert into data_theloai (ma_tloai, ten_tloai) values (678, 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit');
insert into data_theloai (ma_tloai, ten_tloai) values (839, 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis');
insert into data_theloai (ma_tloai, ten_tloai) values (835, 'mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget');
insert into data_theloai (ma_tloai, ten_tloai) values (588, 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec');
insert into data_theloai (ma_tloai, ten_tloai) values (54, 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate');
insert into data_theloai (ma_tloai, ten_tloai) values (319, 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in');
insert into data_theloai (ma_tloai, ten_tloai) values (459, 'ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into data_theloai (ma_tloai, ten_tloai) values (222, 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into data_theloai (ma_tloai, ten_tloai) values (18, 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius');
insert into data_theloai (ma_tloai, ten_tloai) values (723, 'praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into data_theloai (ma_tloai, ten_tloai) values (512, 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem');
insert into data_theloai (ma_tloai, ten_tloai) values (476, 'diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et');
insert into data_theloai (ma_tloai, ten_tloai) values (285, 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel');
insert into data_theloai (ma_tloai, ten_tloai) values (383, 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec');
insert into data_theloai (ma_tloai, ten_tloai) values (116, 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce');
insert into data_theloai (ma_tloai, ten_tloai) values (731, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit');
insert into data_theloai (ma_tloai, ten_tloai) values (522, 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac');
insert into data_theloai (ma_tloai, ten_tloai) values (999, 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi');
insert into data_theloai (ma_tloai, ten_tloai) values (658, 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc');
insert into data_theloai (ma_tloai, ten_tloai) values (724, 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum');
insert into data_theloai (ma_tloai, ten_tloai) values (80, 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet');
insert into data_theloai (ma_tloai, ten_tloai) values (25, 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc');
insert into data_theloai (ma_tloai, ten_tloai) values (483, 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus');
insert into data_theloai (ma_tloai, ten_tloai) values (772, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin');
insert into data_theloai (ma_tloai, ten_tloai) values (762, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis');
insert into data_theloai (ma_tloai, ten_tloai) values (848, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget');
insert into data_theloai (ma_tloai, ten_tloai) values (827, 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus');
insert into data_theloai (ma_tloai, ten_tloai) values (350, 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis');
insert into data_theloai (ma_tloai, ten_tloai) values (35, 'accumsan felis ut at dolor quis odio consequat varius integer ac leo');
insert into data_theloai (ma_tloai, ten_tloai) values (542, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget');
insert into data_theloai (ma_tloai, ten_tloai) values (103, 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into data_theloai (ma_tloai, ten_tloai) values (190, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a');
insert into data_theloai (ma_tloai, ten_tloai) values (853, 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into data_theloai (ma_tloai, ten_tloai) values (485, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem');
insert into data_theloai (ma_tloai, ten_tloai) values (246, 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien');
insert into data_theloai (ma_tloai, ten_tloai) values (496, 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui');
insert into data_theloai (ma_tloai, ten_tloai) values (786, 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero');
insert into data_theloai (ma_tloai, ten_tloai) values (445, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices');
insert into data_theloai (ma_tloai, ten_tloai) values (616, 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into data_theloai (ma_tloai, ten_tloai) values (821, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero');
insert into data_theloai (ma_tloai, ten_tloai) values (662, 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est');
insert into data_theloai (ma_tloai, ten_tloai) values (328, 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id');
insert into data_theloai (ma_tloai, ten_tloai) values (914, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam');
insert into data_theloai (ma_tloai, ten_tloai) values (370, 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer');
insert into data_theloai (ma_tloai, ten_tloai) values (474, 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo');
insert into data_theloai (ma_tloai, ten_tloai) values (357, 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et');
insert into data_theloai (ma_tloai, ten_tloai) values (478, 'ac est lacinia nisi venenatis tristique fusce congue diam id');
insert into data_theloai (ma_tloai, ten_tloai) values (538, 'sem duis aliquam convallis nunc proin at turpis a pede');
insert into data_theloai (ma_tloai, ten_tloai) values (511, 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus');
insert into data_theloai (ma_tloai, ten_tloai) values (121, 'potenti in eleifend quam a odio in hac habitasse platea');
insert into data_theloai (ma_tloai, ten_tloai) values (931, 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into data_theloai (ma_tloai, ten_tloai) values (740, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam');
insert into data_theloai (ma_tloai, ten_tloai) values (178, 'vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur');
insert into data_theloai (ma_tloai, ten_tloai) values (282, 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi');
insert into data_theloai (ma_tloai, ten_tloai) values (991, 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into data_theloai (ma_tloai, ten_tloai) values (638, 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum');
insert into data_theloai (ma_tloai, ten_tloai) values (803, 'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero');
insert into data_theloai (ma_tloai, ten_tloai) values (729, 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices');
insert into data_theloai (ma_tloai, ten_tloai) values (289, 'massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst');
insert into data_theloai (ma_tloai, ten_tloai) values (304, 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit');
insert into data_theloai (ma_tloai, ten_tloai) values (532, 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum');
insert into data_theloai (ma_tloai, ten_tloai) values (990, 'proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate');
insert into data_theloai (ma_tloai, ten_tloai) values (434, 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo');
insert into data_theloai (ma_tloai, ten_tloai) values (130, 'a ipsum integer a nibh in quis justo maecenas rhoncus');
insert into data_theloai (ma_tloai, ten_tloai) values (895, 'semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis');
insert into data_theloai (ma_tloai, ten_tloai) values (380, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar');
insert into data_theloai (ma_tloai, ten_tloai) values (14, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam');
insert into data_theloai (ma_tloai, ten_tloai) values (504, 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into data_theloai (ma_tloai, ten_tloai) values (974, 'tellus nulla ut erat id mauris vulputate elementum nullam varius');
insert into data_theloai (ma_tloai, ten_tloai) values (842, 'nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan');
insert into data_theloai (ma_tloai, ten_tloai) values (837, 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac');
insert into data_theloai (ma_tloai, ten_tloai) values (909, 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa');
insert into data_theloai (ma_tloai, ten_tloai) values (915, 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla');
insert into data_theloai (ma_tloai, ten_tloai) values (612, 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet');
insert into data_theloai (ma_tloai, ten_tloai) values (28, 'vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac');
insert into data_theloai (ma_tloai, ten_tloai) values (946, 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper');
insert into data_theloai (ma_tloai, ten_tloai) values (267, 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras');
insert into data_theloai (ma_tloai, ten_tloai) values (552, 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis');
insert into data_theloai (ma_tloai, ten_tloai) values (536, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient');
insert into data_theloai (ma_tloai, ten_tloai) values (731, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero');
insert into data_theloai (ma_tloai, ten_tloai) values (782, 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus');
insert into data_theloai (ma_tloai, ten_tloai) values (419, 'id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into data_theloai (ma_tloai, ten_tloai) values (851, 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer');
insert into data_theloai (ma_tloai, ten_tloai) values (32, 'lobortis vel dapibus at diam nam tristique tortor eu pede');
insert into data_theloai (ma_tloai, ten_tloai) values (276, 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui');
